config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  get 'group' => 'pages#group', as: 'group'
  get 'admin' => 'pages#admin', as: 'admin'
  get 'table' => 'pages#table', as: 'table'
  get 'invite' => 'pages#invite', as: 'invite'
  get 'team' => 'pages#team', as: 'team'
  get 'table1' => 'pages#table1', as: 'table1'
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
  end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_groups
  has_many :groups, through: :user_groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

    protect_from_forgery with: :exception
  
    before_action :set_redirect_path, unless: :user_signed_in?
  
    def set_redirect_path
      @redirect_path = request.path
    end
  
    def after_sign_in_path_for(resource)
      if params[:redirect_to].present?
        store_location_for(resource, params[:redirect_to])
      elsif request.referer == new_session_url
        super
      else
        stored_location_for(resource) || request.referer || root_path
      end
    end

    def after_sign_up_path_for(resource)
        if params[:redirect_to].present?
          store_location_for(resource, params[:redirect_to])
        elsif request.referer == new_session_url
          super
        else
          stored_location_for(resource) || request.referer || root_path
        end
      end

  end

app/controllers/members_controller.rb
class MembersController < ApplicationController

    
    def show
        @members = Member.all
        
    end
    
    def update
        @member = Member.last
        Member.all.each do |aux|
        aux.update(member_params)
        end
     end

    def create
        @member = Member.new(member_params)

        if @member.save
            redirect_to admin_path
        else
            render "admin"
        end
     end

    
     
    private
    def member_params
        params.required(:member).permit(:firstname, :lastname, :email, :cash)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def group
  end

  def admin
    current_user.update(:admin=>true)
    @member = Member.new
    @members = Member.all
  end

  def table
    @members = Member.all
  end

  def table1
    @members = Member.all
  end
  
  def team
      current_user.update(:viewer=>true)
      @member = Member.last
    Member.all.each do |aux|
    aux.update(cash: params[:cash])
    end
  end

  def invite
    
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
    def login_options
         @redirect_path ? {redirect_to: @redirect_path} : {}
            
    end
    
    def register_options
        @redirect_path ? {redirect_to: @redirect_path} : {}
    end
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
      return "" unless devise_error_messages?
  
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t("errors.messages.not_saved",
                        :count => resource.errors.count,
                        :resource => resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div id="error_explanation">
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
      HTML
  
      html.html_safe
    end
  
    def devise_error_messages?
      !resource.errors.empty?
    end
  
  end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/members/show.html.erb
<table>
<thead>
  <tr>
    <th>Nome</th>
    
    <th></th>
    <th>Pagamento</th>
  </tr>
</thead>
<% @member.each do |item| %>
<tbody>
  <tr>
    
     <td><%= item.firstname %></td> 
    <td><%= item.lastname %></td>
   
  </tr>
 
  
</tbody>
</table>
<% end %>

app/views/pages/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'admin.css' %>


<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>
</header>
<body>

<div id="members-box">


<div class="box">

<%= form_for @member do |f| -%>

<h1>Caixa da Equipe</h1>

<div class="field">
    <%= f.label :caixa %><br />
    <%= f.text_field :cash, autofocus: true %>
</div>

<h1>Adicione integrantes em sua equipe</h1>
<hr>
<div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :firstname, autofocus: true %>
</div>
<div class="field">
  <%= f.label :sobrenome %><br />
  <%= f.text_field :lastname, autofocus: true %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.email_field :email, autofocus: true %>
</div>
<br />
&nbsp&nbsp
<%= submit_tag 'Adicionar Membro' %>

<% end -%>

<hr>
<div class="members">
<h1>Integrantes cadastrados</h1>
<hr>
<class = "integers">
<% if !@members.empty? %>
    <% @members.each do |item| %>
        <br />
        <%= item.firstname %> <%= item.lastname %> <br />
    <% end %>
    <br />
    <%= form_tag team_path, method: :get do %>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        <%= submit_tag 'Ir para grupo' %>
        
      <% end %>
      
<% end %>
</div>
</body>
</html>

app/views/pages/group.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'cadastro.css' %>
</head>

<body>


<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>
</header>
<body>
</br></br>
<% if current_user.admin %>
<center>
<%= image_tag("giphy.gif", :class => "giphy" ) %>
</br></br>
<p1>  Bem vinda(o) de novo!.</p1>
<center></br></br></br></br></br></br></br></br></br></br></br>
<%= form_tag admin_path, method: :get do %>
  <%= submit_tag 'Modificar Controle' %>
<% end %>
<%elsif current_user.viewer%>
<%= form_tag table_path, method: :get do %>
  <%= submit_tag 'Visualizar Controle' %>
<% end %>
<% else %>
<center>
<%= image_tag("sorry.gif", :class => "sorry" ) %>
</br></br>
<p1>  Desculpe, você não está registrado em nenhuma equipe.</p1>
</br></br>
 <%= form_tag admin_path, method: :get do %>
    <%= submit_tag 'Criar nova equipe' %>
  <% end %>
<% end %>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'application.css' %>
</head>

<body>


<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>


    <nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                
                <%= link_to 'Controle de Equipe', group_path %>
                &nbsp &nbsp
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>

</header>

<body>

<div class="banner">
<%= image_tag("banner.png", :alt => "banner_image", :class => "responsive") %>
<h1> <center>&nbsp&nbspA &nbsp&nbspPlataforma </h1>

<p1>
<center>
A Controlo é uma plataforma de gastos coletivos, incentivando a transparência e melhor participação nas finanças de equipes.</br>
Comece a usar e melhore a velocidade de comunicação e facilidade na visualização das despesas!
</center>
</p1>

<nav>
        <ul>
            <lia><a href="#">
                <%= link_to 'Comece já', new_user_session_path(login_options) %>
            </a></lia>

            </ul>
</nav>

</div>

</body>


</html>

app/views/pages/invite.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'cadastro.css' %>

<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
    <ul>
        <% if current_user %>
        <%= form_tag team_path, method: :get do %>
            <%= submit_tag 'Visualizar equipe' %>
            &nbsp &nbsp
            <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
        <% end %>
        
        <% else %>
    <li><a href="#">
    <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
    </a></li>

    <li><a href="#">
        <%= link_to 'Entrar', new_user_session_path(login_options) %>
    </a></li>
            
            
    </ul>
    </nav>
<% end %>
</header>

<body>
<center>
<%= image_tag("email.gif", :class => "sorry" ) %>
<p1>
<center>
<b>Você foi convidado para participar da Controlo!</b>
</br></br>
A Controlo é uma plataforma de gastos coletivos, incentivando a transparência e melhor participação nas finanças de equipes.</br>
Comece a usar e melhore a velocidade de comunicação e facilidade na visualização das despesas!
</center>
</p1>

</body>
</html>

app/views/pages/table.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'table.css' %>
</head>

<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>
</header>
<body>

<h1><center>Mensalidade</h1>
<div class="box">
<table>
<thead>
  <tr>
  
    <th><label class="tabt"><b><center>Nome</b><br/></th>
    <th><b>_____________________________________________________</b></th>
    <th><label class="tabt"><b>Pagamento</b><br/></th>
    </div>
  </tr>
</thead>
<% @members.each do |item| %>
<tbody>
  <tr>
  &nbsp&nbsp
    <div class="tab">
    
    <td><label class="tab"><%=item.firstname %></td> 
    <th>_____________________________________________________</th>
    <td><label class="check">Pago
    <input type="checkbox" id="myCheck"  onclick="myFunction()">
    <span class="checkmark"></span>
  </label></td>
    </div>
    
    <br/>
   
  </tr>
</tbody>
<% end %>
</table>
</div>
</body>
</html>

app/views/pages/table1.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'table.css' %>
</head>

<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>
</header>
<body>

<h1><center>Transporte</h1>
<div class="box">
<table>
<thead>
  <tr>
  
    <th><label class="tabt"><b><center>Nome</b><br/></th>
    <th><b>_____________________________________________________</b></th>
    <th><label class="tabt"><b>Pagamento</b><br/></th>
    </div>
  </tr>
</thead>
<% @members.each do |item| %>
<tbody>
  <tr>
  &nbsp&nbsp
    <div class="tab">
    
    <td><label class="tab"><%=item.firstname %></td> 
    <th>_____________________________________________________</th>
    <td><label class="check">Pago
    <input type="checkbox" id="myCheck"  onclick="myFunction()">
    <span class="checkmark"></span>
  </label></td>
    </div>
    
    <br/>
   
  </tr>
</tbody>
<% end %>
</table>
</div>
</body>
</html>

app/views/pages/team.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<%= stylesheet_link_tag 'cadastro.css' %>
<header>
<div class="container">
<%= image_tag("controlo.png", :class => "logo", :height=> 80, :width=> 280 ) %>

<nav>
        <ul>
            <% if current_user %>
            <li><a href="#">
                <%= link_to 'Sair', destroy_user_session_path, 
                method: :delete %>
            </a></li>
            <% else %>
            <li><a href="#">
                <%= link_to 'Cadastrar', new_user_registration_path(register_options) %>
            </a></li>

            <li><a href="#">
                <%= link_to 'Entrar', new_user_session_path(login_options) %>
            </a></li>
            <% end %>
        </ul>
    </nav>
</div>
</header>
<body>

    <div class="field">
    <% if current_user.admin %>
    <center>
    <%= form_for @member do |f| -%>
    <%= f.label :Caixa %><br />
    <%= f.text_field :cash, autofocus: true %>
    <%= submit_tag 'Atualizar Caixa' %>
    <% end %>
</div>
<% end -%>
</head>
<body>
<center>
<%= form_tag table_path, method: :get do %>
    <%= submit_tag 'Mensalidade' %>
    <% end %>
    <%= form_tag table1_path, method: :get do %>
        <%= submit_tag 'Transporte' %>
        <% end %>




</body>
</html>